// <auto-generated />
using System;
using Archive_DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Archive_DbContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629142111_update-relations-chapters")]
    partial class updaterelationschapters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Archive_DbContext.Entities.ChapterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Chapter");
                });

            modelBuilder.Entity("Archive_DbContext.Entities.FamilyTreeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MainUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MainUserId");

                    b.ToTable("FamilyTree");
                });

            modelBuilder.Entity("Archive_DbContext.Entities.FileResourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ChapterEntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ResourceUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChapterEntityId");

                    b.ToTable("File");
                });

            modelBuilder.Entity("Archive_DbContext.Entities.PersonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ArchiveId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DayOfDeath")
                        .HasColumnType("date");

                    b.Property<Guid?>("FatherId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("MotherId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ShortBiography")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TreeLVL")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Archive_DbContext.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("FamilyTreeEntityUserEntity", b =>
                {
                    b.Property<Guid>("FamilyTreesId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("char(36)");

                    b.HasKey("FamilyTreesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("FamilyTreeUsers", (string)null);
                });

            modelBuilder.Entity("Archive_DbContext.Entities.ChapterEntity", b =>
                {
                    b.HasOne("Archive_DbContext.Entities.PersonEntity", "Person")
                        .WithMany("Chapters")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Archive_DbContext.Entities.FamilyTreeEntity", b =>
                {
                    b.HasOne("Archive_DbContext.Entities.UserEntity", null)
                        .WithMany("OwnedTrees")
                        .HasForeignKey("MainUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Archive_DbContext.Entities.FileResourceEntity", b =>
                {
                    b.HasOne("Archive_DbContext.Entities.ChapterEntity", null)
                        .WithMany("Files")
                        .HasForeignKey("ChapterEntityId");
                });

            modelBuilder.Entity("Archive_DbContext.Entities.PersonEntity", b =>
                {
                    b.HasOne("Archive_DbContext.Entities.FamilyTreeEntity", "FamilyTree")
                        .WithMany("Persons")
                        .HasForeignKey("ArchiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamilyTree");
                });

            modelBuilder.Entity("FamilyTreeEntityUserEntity", b =>
                {
                    b.HasOne("Archive_DbContext.Entities.FamilyTreeEntity", null)
                        .WithMany()
                        .HasForeignKey("FamilyTreesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archive_DbContext.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Archive_DbContext.Entities.ChapterEntity", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Archive_DbContext.Entities.FamilyTreeEntity", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("Archive_DbContext.Entities.PersonEntity", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("Archive_DbContext.Entities.UserEntity", b =>
                {
                    b.Navigation("OwnedTrees");
                });
#pragma warning restore 612, 618
        }
    }
}
