// <auto-generated />
using System;
using Archive_DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Archive_DbContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Archive_DbContext.Entities.ChapterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("PersonEntityId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PersonEntityId");

                    b.ToTable("Chapter");
                });

            modelBuilder.Entity("Archive_DbContext.Entities.FamilyTreeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MainUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("usersId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FamilyTree");
                });

            modelBuilder.Entity("Archive_DbContext.Entities.FileResourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ChapterEntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ResourceUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChapterEntityId");

                    b.ToTable("File");
                });

            modelBuilder.Entity("Archive_DbContext.Entities.PersonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DayOfDeath")
                        .HasColumnType("date");

                    b.Property<Guid?>("FamilyTreeEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("FatherId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("MotherId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ShortBiography")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TreeLVL")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FamilyTreeEntityId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Archive_DbContext.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Archive_DbContext.Entities.ChapterEntity", b =>
                {
                    b.HasOne("Archive_DbContext.Entities.PersonEntity", null)
                        .WithMany("Chapters")
                        .HasForeignKey("PersonEntityId");
                });

            modelBuilder.Entity("Archive_DbContext.Entities.FileResourceEntity", b =>
                {
                    b.HasOne("Archive_DbContext.Entities.ChapterEntity", null)
                        .WithMany("Files")
                        .HasForeignKey("ChapterEntityId");
                });

            modelBuilder.Entity("Archive_DbContext.Entities.PersonEntity", b =>
                {
                    b.HasOne("Archive_DbContext.Entities.FamilyTreeEntity", null)
                        .WithMany("Persons")
                        .HasForeignKey("FamilyTreeEntityId");
                });

            modelBuilder.Entity("Archive_DbContext.Entities.ChapterEntity", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Archive_DbContext.Entities.FamilyTreeEntity", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("Archive_DbContext.Entities.PersonEntity", b =>
                {
                    b.Navigation("Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
